<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.kuro.exceptions.hendler.ConsoleErrorHandlerTest" tests="4" skipped="0" failures="0" errors="0" timestamp="2025-03-14T15:50:55" hostname="KURO" time="0.238">
  <properties/>
  <testcase name="handle_withApplicationException_printsToConsole()" classname="org.kuro.exceptions.hendler.ConsoleErrorHandlerTest" time="0.222"/>
  <testcase name="tearDown()" classname="org.kuro.exceptions.hendler.ConsoleErrorHandlerTest" time="0.003"/>
  <testcase name="handle_withFileException_includesFilePathInDetails()" classname="org.kuro.exceptions.hendler.ConsoleErrorHandlerTest" time="0.005"/>
  <testcase name="handleUnexpected_withException_printsToConsole()" classname="org.kuro.exceptions.hendler.ConsoleErrorHandlerTest" time="0.004"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
